-- ============================================================
-- SUBJECT-BASED ACTIVITY SYSTEM
-- Safe migration for the existing tutoring platform
-- ============================================================

begin;

-- ------------------------------------------------------------
-- 1) SUBJECTS
-- ------------------------------------------------------------

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  name text not null,
  university text,
  description text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists subjects_name_university_unique
  on public.subjects (lower(name), coalesce(university, ''));

-- ------------------------------------------------------------
-- 2) STUDENT <-> SUBJECT ASSIGNMENTS
--
-- We intentionally inherit the EXISTING students.id type instead
-- of assuming UUID vs bigint.
-- ------------------------------------------------------------

create table if not exists public.student_subjects as
select
  s.id as student_id,
  cast(null as bigint) as subject_id,
  cast(true as boolean) as active,
  cast(now() as timestamptz) as assigned_at
from public.students s
with no data;

alter table public.student_subjects
  alter column student_id set not null;

alter table public.student_subjects
  alter column subject_id set not null;

alter table public.student_subjects
  alter column active set default true;

alter table public.student_subjects
  alter column assigned_at set default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'student_subjects_pkey'
      and conrelid = 'public.student_subjects'::regclass
  ) then
    alter table public.student_subjects
      add constraint student_subjects_pkey
      primary key (student_id, subject_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'student_subjects_student_id_fkey'
      and conrelid = 'public.student_subjects'::regclass
  ) then
    alter table public.student_subjects
      add constraint student_subjects_student_id_fkey
      foreign key (student_id)
      references public.students(id)
      on delete cascade;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'student_subjects_subject_id_fkey'
      and conrelid = 'public.student_subjects'::regclass
  ) then
    alter table public.student_subjects
      add constraint student_subjects_subject_id_fkey
      foreign key (subject_id)
      references public.subjects(id)
      on delete cascade;
  end if;
end $$;

create index if not exists student_subjects_student_idx
  on public.student_subjects(student_id);

create index if not exists student_subjects_subject_idx
  on public.student_subjects(subject_id);

-- ------------------------------------------------------------
-- 3) LINK ACTIVITIES TO SUBJECTS
-- ------------------------------------------------------------

alter table public.activity_requirements
  add column if not exists subject_id bigint;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'activity_requirements_subject_id_fkey'
      and conrelid = 'public.activity_requirements'::regclass
  ) then
    alter table public.activity_requirements
      add constraint activity_requirements_subject_id_fkey
      foreign key (subject_id)
      references public.subjects(id)
      on delete restrict;
  end if;
end $$;

create index if not exists activity_requirements_subject_idx
  on public.activity_requirements(subject_id);

-- ------------------------------------------------------------
-- 4) BACKFILL SUBJECTS FROM THE EXISTING students.subject TEXT
--
-- We keep students.subject intact for compatibility.
-- ------------------------------------------------------------

insert into public.subjects (name, university)
select distinct
  trim(s.subject),
  nullif(trim(s.university), '')
from public.students s
where nullif(trim(coalesce(s.subject, '')), '') is not null
on conflict do nothing;

-- Assign existing students to the matching subject.
insert into public.student_subjects (student_id, subject_id, active)
select
  st.id,
  sub.id,
  true
from public.students st
join public.subjects sub
  on lower(sub.name) = lower(trim(st.subject))
 and coalesce(sub.university, '') = coalesce(nullif(trim(st.university), ''), '')
where nullif(trim(coalesce(st.subject, '')), '') is not null
on conflict (student_id, subject_id)
do update set active = true;

-- Existing activity_requirements intentionally keep subject_id = NULL.
-- The redesigned manager displays these as "Legacy / Unassigned".
-- This prevents activities from being silently attached to the wrong subject.

-- ------------------------------------------------------------
-- 5) RLS
-- Match the current app's authenticated-admin pattern.
-- ------------------------------------------------------------

alter table public.subjects enable row level security;
alter table public.student_subjects enable row level security;

drop policy if exists "Authenticated users manage subjects"
  on public.subjects;

create policy "Authenticated users manage subjects"
  on public.subjects
  for all
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated users manage student subjects"
  on public.student_subjects;

create policy "Authenticated users manage student subjects"
  on public.student_subjects
  for all
  to authenticated
  using (true)
  with check (true);

commit;
